services:
  - type: web
    name: techshop-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FINNHUB_API_KEY
        sync: false
